
# Лабораторна робота №5 (варіант 1)

**Мета роботи:** отримати базові знання та навички по роботі з бібліотекою **NumPy**.

In [2]:

import numpy as np
from time import perf_counter

def timed(f):
    def w(*a, **k):
        t0 = perf_counter(); r = f(*a, **k); t1 = perf_counter()
        return r, (t1 - t0)
    return w

def show_cmp(title, res_np, t_np, res_it, t_it, scalar=False):
    ok = (res_np == res_it) if scalar else np.allclose(res_np, res_it)
    print(f"{title}\n  NumPy: {t_np:.6f}s  |  Ітеративно: {t_it:.6f}s  |  збіг: {ok}\n")



## Вправа 1 
Вводиться число n. Вивести масив разміра nхn, в якому по 
діагоналі йдуть числа від 1 до n, а інші числа рівні 0


In [3]:
@timed
def ex1_numpy(n: int):
    a = np.zeros((n, n), dtype=int)
    a[np.diag_indices(n)] = np.arange(1, n+1)
    return a

@timed
def ex1_iter(n: int):
    a = [[0]*n for _ in range(n)]
    for i in range(n):
        a[i][i] = i + 1
    return np.array(a, dtype=int)


n = 5
res_np, t_np = ex1_numpy(n)
res_it, t_it = ex1_iter(n)
show_cmp("Вправа 1", res_np, t_np, res_it, t_it)

Вправа 1
  NumPy: 0.000112s  |  Ітеративно: 0.000016s  |  збіг: True




## Вправа 6 
З клавіатури вводиться масив. Замінити всі ненульові елементи на -1


In [4]:

@timed
def ex6_numpy(arr):
    a = np.asarray(arr, dtype=int)
    return np.where(a != 0, -1, 0)

@timed
def ex6_iter(arr):
    out = [(-1 if x != 0 else 0) for x in arr]
    return np.array(out, dtype=int)

sample = [3,4,0,9,7,0,6,0,4,0,3]
res_np, t_np = ex6_numpy(sample); res_it, t_it = ex6_iter(sample)
print(res_np)
show_cmp("Вправа 6", res_np, t_np, res_it, t_it)


[-1 -1  0 -1 -1  0 -1  0 -1  0 -1]
Вправа 6
  NumPy: 0.000114s  |  Ітеративно: 0.000009s  |  збіг: True




## Вправа 7 
З клавіатури вводиться масив. Замінити всі нульові елементи на -1.

In [5]:

@timed
def ex7_numpy(arr):
    a = np.asarray(arr, dtype=int)
    return np.where(a == 0, -1, a)

@timed
def ex7_iter(arr):
    out = [(-1 if x == 0 else x) for x in arr]
    return np.array(out, dtype=int)

sample = [3,4,0,6,5,0,3,0,4]
res_np, t_np = ex7_numpy(sample); res_it, t_it = ex7_iter(sample)
print(res_np)
show_cmp("Вправа 7", res_np, t_np, res_it, t_it)


[ 3  4 -1  6  5 -1  3 -1  4]
Вправа 7
  NumPy: 0.000067s  |  Ітеративно: 0.000007s  |  збіг: True




## Вправа 9 
Вводиться число n. Створити масив значень від n до 0.


In [6]:

@timed
def ex9_numpy(n:int):
    return np.arange(n, -1, -1, dtype=int)

@timed
def ex9_iter(n:int):
    return np.array([i for i in range(n, -1, -1)], dtype=int)

res_np, t_np = ex9_numpy(10); res_it, t_it = ex9_iter(10)
print(res_np)
show_cmp("Вправа 9", res_np, t_np, res_it, t_it)


[10  9  8  7  6  5  4  3  2  1  0]
Вправа 9
  NumPy: 0.000023s  |  Ітеративно: 0.000015s  |  збіг: True




## Вправа 10 
Вводиться числа n i m. Створити масив випадкових значень n на m
і обчислити мінімальне, максимальне значення, середнє та середньо 
квадратичне відхилення, округлене до 3 знаків після коми


In [7]:

def stats_tuple(a):
    return (float(a.min()), float(a.max()), float(a.mean()), float(a.std()))

@timed
def ex10_numpy(a):
    mn, mx, mean, std = stats_tuple(a)
    return tuple(round(x, 3) for x in (mn, mx, mean, std))

@timed
def ex10_iter(a):
    n, m = len(a), len(a[0])
    flat = [x for row in a for x in row]
    s = sum(flat)
    mean = s / (n*m)
    var = sum((x-mean)**2 for x in flat) / (n*m)
    std = var**0.5
    mn, mx = min(flat), max(flat)
    return (round(mn,3), round(mx,3), round(mean,3), round(std,3))

rng = np.random.default_rng(42)
A = rng.random((4,5))
res_np, t_np = ex10_numpy(A.copy()); res_it, t_it = ex10_iter(A.tolist())
print("мінімум:", res_np[0], "максимум:", res_np[1], "середнє:", res_np[2], "стандартне відхилення:", res_np[3])
show_cmp("Вправа 10", np.array(res_np), t_np, np.array(res_it), t_it)


мінімум: 0.064 максимум: 0.976 середнє: 0.574 стандартне відхилення: 0.277
Вправа 10
  NumPy: 0.000248s  |  Ітеративно: 0.000010s  |  збіг: True




## Вправа 11 
Створити масив одиниць розміром n х n та додати до нього 
«рамку», сформовану з 0


In [8]:

@timed
def ex11_numpy(n:int):
    a = np.ones((n+2, n+2), dtype=int)
    a[0,:] = a[-1,:] = a[:,0] = a[:,-1] = 0
    return a

@timed
def ex11_iter(n:int):
    N = n+2
    a = [[1]*N for _ in range(N)]
    for j in range(N):
        a[0][j] = a[N-1][j] = 0
    for i in range(N):
        a[i][0] = a[i][N-1] = 0
    return np.array(a, dtype=int)

res_np, t_np = ex11_numpy(4); res_it, t_it = ex11_iter(4)
print(res_np)
show_cmp("Вправа 11", res_np, t_np, res_it, t_it)


[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]]
Вправа 11
  NumPy: 0.000151s  |  Ітеративно: 0.000049s  |  збіг: True




## Вправа 15 
Заповнити парні стовбчики матриці розміром n х n одиницями, а 
непарні – нулями.

In [9]:

@timed
def ex15_numpy(n:int):
    a = np.zeros((n,n), dtype=int)
    a[:, 1::2] = 1
    return a

@timed
def ex15_iter(n:int):
    a = [[0]*n for _ in range(n)]
    for j in range(n):
        v = 1 if ((j+1) % 2 == 0) else 0
        for i in range(n):
            a[i][j] = v
    return np.array(a, dtype=int)

res_np, t_np = ex15_numpy(5); res_it, t_it = ex15_iter(5)
print(res_np)
show_cmp("Вправа 15", res_np, t_np, res_it, t_it)


[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Вправа 15
  NumPy: 0.000022s  |  Ітеративно: 0.000018s  |  збіг: True




## Вправа 17 
Заповнити вектор значеннями від 0 до n. Замінити знаки для всіх 
значеннь, що менші за n/2 та більші за 3n/4 на протилежні

In [10]:

@timed
def ex17_numpy(n:int):
    v = np.arange(0, n+1, dtype=int)
    mask = (v < n/2) | (v > 3*n/4)
    v = np.where(mask, -v, v)
    return v

@timed
def ex17_iter(n:int):
    v = []
    for x in range(0, n+1):
        if x < n/2 or x > 3*n/4:
            v.append(-x)
        else:
            v.append(x)
    return np.array(v, dtype=int)

res_np, t_np = ex17_numpy(10); res_it, t_it = ex17_iter(10)
print(res_np)
show_cmp("Вправа 17", res_np, t_np, res_it, t_it)


[  0  -1  -2  -3  -4   5   6   7  -8  -9 -10]
Вправа 17
  NumPy: 0.000204s  |  Ітеративно: 0.000020s  |  збіг: True




## Вправа 18
Згенерувати вектор з n випадкових чисел в діапазоні від 0 до 99. 
Визначити кількість унікальних чисел в послідовності


In [11]:

@timed
def ex18_numpy(n:int, seed=7):
    rng = np.random.default_rng(seed)
    v = rng.integers(0, 100, size=n, dtype=int)
    return int(np.unique(v).size)

@timed
def ex18_iter(n:int, seed=7):
    rng = np.random.default_rng(seed)
    v = list(map(int, rng.integers(0, 100, size=n)))
    return len(set(v))

res_np, t_np = ex18_numpy(30); res_it, t_it = ex18_iter(30)
print("унікальних чисел:", res_np)
show_cmp("Вправа 18", res_np, t_np, res_it, t_it, scalar=True)


унікальних чисел: 29
Вправа 18
  NumPy: 0.003418s  |  Ітеративно: 0.000327s  |  збіг: True




# Завдання 2 
Розв’язати систему за допомогою формул Крамера і виконати перевірку за 
допомогою:
a) матричного множення;
b) оберненої матриці;
c) функції numpy.linalg.solve().
Порівняти всі рішення за допомогою функції numpy.allclose()


In [12]:

A = np.array([
    [1,  1,  2,  3],
    [3, -1, -1, -2],
    [2, -3, -1, -1],
    [1,  2,  3, -1]
], dtype=float)
b = np.array([1, -4, -6, -4], dtype=float)

@timed
def solve_cramer(A, b):
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    n = A.shape[0]
    detA = np.linalg.det(A)
    if abs(detA) < 1e-12:
        raise ValueError("det(A)=0, система вироджена")
    x = np.zeros(n)
    for j in range(n):
        Aj = A.copy()
        Aj[:, j] = b
        x[j] = np.linalg.det(Aj) / detA
    return x

@timed
def solve_via_inverse(A, b):
    return np.linalg.inv(A) @ b

@timed
def solve_via_solve(A, b):
    return np.linalg.solve(A, b)

x_cr, t_cr = solve_cramer(A, b)
x_inv, t_inv = solve_via_inverse(A, b)
x_sv , t_sv  = solve_via_solve(A, b)

print("Розв’язок (Крамер):", np.round(x_cr, 6))
print(f"Час: Крамер {t_cr:.6f}s | inverse {t_inv:.6f}s | solve {t_sv:.6f}s")
print("A@x ≈ b:", np.allclose(A @ x_cr, b))
print("Крамер vs inverse:", np.allclose(x_cr, x_inv))
print("Крамер vs solve  :", np.allclose(x_cr, x_sv))


Розв’язок (Крамер): [-0.555556  1.888889 -2.        1.222222]
Час: Крамер 0.001659s | inverse 0.000333s | solve 0.000396s
A@x ≈ b: True
Крамер vs inverse: True
Крамер vs solve  : True



# Завдання 3 
Обчислити значення матричного виразу 
а) з використанням універсальних функцій бібліотеки NumPy.
b) за допомогою ітеративних конструкцій (з використанням циклів, 
спискових включень тощо).
с) для обох випадків підрахувати час виконання скрипту та зробити 
висновок
Порівняти всі рішення за допомогою функції numpy.allclose()

In [13]:

A3 = np.array([[ 2, 3,-1],
               [ 4, 5, 2],
               [-1, 0, 7]], dtype=float)
B3 = np.array([[-1, 0, 5],
               [ 0, 1, 3],
               [ 2,-2, 4]], dtype=float)

@timed
def expr_numpy(A, B):
    return 2 * (A + B) @ (2*B - A)

def mat_add(X, Y):
    n, m = X.shape
    Z = [[X[i, j] + Y[i, j] for j in range(m)] for i in range(n)]
    return np.array(Z, dtype=float)

def mat_sub(X, Y):
    n, m = X.shape
    Z = [[X[i, j] - Y[i, j] for j in range(m)] for i in range(n)]
    return np.array(Z, dtype=float)

def mat_mul(X, Y):
    n, m = X.shape
    m2, k = Y.shape
    assert m == m2
    Z = [[0.0]*k for _ in range(n)]
    for i in range(n):
        for j in range(k):
            s = 0.0
            for t in range(m):
                s += X[i, t]*Y[t, j]
            Z[i][j] = s
    return np.array(Z, dtype=float)

@timed
def expr_iter(A, B):
    S = mat_add(A, B)
    T = mat_sub(2*B, A)
    M = mat_mul(S, T)
    return 2 * M

res_np, t_np = expr_numpy(A3, B3)
res_it, t_it = expr_iter(A3, B3)

print("Результат NumPy:\n", res_np)
print(f"Час: NumPy {t_np:.6f}s | Ітеративно {t_it:.6f}s")
print("allclose:", np.allclose(res_np, res_it))


Результат NumPy:
 [[   8.  -56.   54.]
 [ -30. -100.  146.]
 [ 118.  -82.   28.]]
Час: NumPy 0.000064s | Ітеративно 0.000058s
allclose: True
